[project]
name = "spml-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.5",
    "torch>=2.9.1",
    "torch-geometric>=2.7.0",
]
